2018-06-29 11:14:13,438 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-06-29 11:14:32,678 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:14:33,058 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:33,499 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:58,797 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:48:11,403 [HttpRunnerManager:151] [operation:add_case_data] [INFO]- 的用例添加成功: {'test': {'request': {'method': 'POST', 'url': ''}, 'name': '的'}}
2018-06-29 11:48:48,076 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:34:18,047 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:18,057 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:18,268 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,270 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,276 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,278 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,296 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:18,299 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:18,352 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,364 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,370 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,383 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,578 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/favicon.ico
2018-07-02 13:34:21,442 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:21,445 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,449 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:21,484 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,487 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,492 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:21,508 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,516 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:21,519 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:21,531 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,540 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,545 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,424 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:22,426 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:22,429 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,465 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,466 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,468 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,480 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,483 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:22,490 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:22,498 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,506 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,509 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:35:30,488 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:48:28,352 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:53:41,984 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:53:49,147 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:54:04,117 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:54:07,459 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:57:09,661 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:57:11,824 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:39,039 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:04:44,830 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:54,650 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:06:02,565 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/config_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 413, in config_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:24:14,328 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:24:16,921 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:27:17,963 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:44,949 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:47,983 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:28:16,257 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:28:18,192 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:16,138 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:20,563 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:24,899 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:37:26,773 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:30,837 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:37:33,775 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:39:25,603 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:39:27,918 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:43:42,829 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:43:44,932 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:47:52,728 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:47:54,981 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:55:50,890 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:55:53,036 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:57:17,859 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/module_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 345, in module_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 433, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '用例_quant_login_out(登入登出)'
2018-07-02 14:59:50,449 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:59:52,333 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2019-10-09 13:00:12,148 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-10-09 13:00:22,138 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/login/
Traceback (most recent call last):
  File "D:\python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-1\HttpRunnerManager\activator.py", line 10, in process
    app = __import__("%s.views" % app)
  File "D:\HttpRunnerManager-1\ApiManager\views.py", line 17, in <module>
    from ApiManager.tasks import main_hrun
  File "D:\HttpRunnerManager-1\ApiManager\tasks.py", line 16, in <module>
    from httprunner import HttpRunner, logger
ImportError: cannot import name 'HttpRunner'
2019-10-09 13:03:52,591 [HttpRunnerManager:55] [views:login] [INFO]- lixiaofeng 登录成功
2019-10-09 13:10:35,402 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
httprunner.exceptions.ParamsError: invalid validator: {'check': 'message', 'comparator': 'equals', 'expected': 'query result is empty'}
2019-10-09 13:13:49,164 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- ceshi 1111用例添加成功: {'test': {'request': {'url': '', 'method': 'POST'}, 'name': 'ceshi 1111', 'validate': [{'comparator': 'equals', 'check': '2321312', 'expected': '31321321321'}]}}
2019-10-09 13:17:58,348 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expected': 'query result is empty'}]}}
2019-10-09 13:18:03,205 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expected': 'query result is empty'}]}}
2019-10-09 13:18:19,900 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message1', 'expected': 'query result is empty'}]}}
2019-10-09 13:18:48,933 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message1', 'expected': 'query result is empty'}]}}
2019-10-09 13:19:26,463 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 12312312用例添加成功: {'test': {'request': {'url': '', 'method': 'POST'}, 'name': '12312312', 'validate': [{'comparator': 'equals', 'check': '2312321', 'expected': '21321312'}]}}
2019-10-09 13:22:33,873 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
httprunner.exceptions.ParamsError: invalid validator: {'check': 'message1', 'comparator': 'equals', 'expected': 'query result is empty'}
2019-10-09 13:22:55,054 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expected': 'query result is empty'}]}}
2019-10-09 13:23:49,946 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
httprunner.exceptions.ParamsError: invalid validator: {'check': 'message1', 'comparator': 'equals', 'expected': 'query result is empty'}
2019-10-09 13:24:51,445 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}]}}
2019-10-09 13:25:07,878 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'query result is empty'}]}}
2019-10-09 13:25:19,397 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'query result is empty'}]}}
2019-10-09 13:51:57,407 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '200'}]}}
2019-10-09 13:52:08,520 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '200'}]}}
2019-10-09 13:54:29,112 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '赵小刀98353'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '10022'}]}}
2019-10-09 13:54:34,292 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '一加8手机发布会1733'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '10022'}]}}
2019-10-09 13:56:15,901 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '10022'}]}}
2019-10-09 13:56:28,846 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '200'}]}}
2019-10-09 13:56:44,790 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': ''}], 'variables': [{'status': '200'}]}}
2019-10-09 13:57:41,798 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'success'}]}}
2019-10-09 13:57:48,317 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'success'}], 'variables': [{'status': '200'}]}}
2019-10-09 13:59:00,464 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
OSError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
OSError: timed out
2019-10-09 14:05:30,357 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 14:05:44,815 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}], 'variables': [{'status': '200'}]}}
2019-10-09 14:06:37,678 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.content.message', 'expect': 'success'}]}}
2019-10-09 14:06:52,392 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.content.message', 'expect': 'success'}]}}
2019-10-09 14:10:18,128 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'success'}]}}
2019-10-09 14:10:26,556 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'success'}]}}
2019-10-09 14:10:59,740 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾测试用例用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'GET', 'params': {'name': '卢红梅'}}, 'name': '查询嘉宾测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 14:11:11,343 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 14:14:09,079 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会测试用例用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': '阎娜发布会'}}, 'name': '查询发布会测试用例', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 15:50:48,259 [HttpRunnerManager:55] [views:login] [INFO]- lixiaofeng 登录成功
2019-10-09 17:29:13,370 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
httprunner.exceptions.ParamsError: Invalid testcase path or testcases: D:\HttpRunnerManager-1\suite\2019-10-09 17-29-13-367
2019-10-09 20:38:12,153 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-10-09 20:38:22,828 [HttpRunnerManager:60] [views:login] [INFO]- lixiaofeng 登录失败, 请检查用户名或者密码
2019-10-09 20:38:28,825 [HttpRunnerManager:55] [views:login] [INFO]- lixiaofeng 登录成功
2019-10-09 22:35:02,035 [HttpRunnerManager:62] [operation:add_project_data] [INFO]- 项目添加成功：{'project_name': 'guest项目', 'responsible_name': 'lee', 'test_user': 'lee', 'dev_user': 'lee', 'publish_app': 'web', 'simple_desc': '', 'other_desc': ''}
2019-10-09 22:35:17,134 [HttpRunnerManager:110] [operation:add_module_data] [INFO]- 模块添加成功：{'module_name': '查询功能', 'test_user': 'lee', 'simple_desc': '', 'other_desc': '', 'belong_project': <ProjectInfo: ProjectInfo object (1)>}
2019-10-09 22:40:16,707 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 查询发布会接口用例添加成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'data': {'name': 'keep手环发布会'}}, 'name': '查询发布会接口', 'validate': [{'comparator': 'equals', 'check': 'message', 'expect': 'success'}]}}
2019-10-09 22:41:29,005 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会接口用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'data': {'name': 'keep手环发布会'}}, 'name': '查询发布会接口', 'validate': [{'comparator': 'equals', 'check': 'conten.message', 'expect': ''}]}}
2019-10-09 22:43:24,359 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会接口用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'data': {'name': 'keep手环发布会'}}, 'name': '查询发布会接口', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 22:45:07,460 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会接口用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'data': {'name': 'keep手环发布会'}}, 'name': '查询发布会接口', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 22:45:50,767 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询发布会接口用例更新成功: {'test': {'request': {'url': '/get_event_list/', 'method': 'GET', 'params': {'name': 'keep手环发布会'}}, 'name': '查询发布会接口', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 22:47:38,480 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 查询嘉宾接口用例添加成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'POST', 'params': {'name': '\t李健'}}, 'name': '查询嘉宾接口', 'validate': [{'comparator': 'equals', 'check': 'conten.message', 'expect': 'success'}]}}
2019-10-09 22:48:29,279 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 查询嘉宾接口用例更新成功: {'test': {'request': {'url': '/get_guest_list/', 'method': 'POST', 'params': {'name': '李健'}}, 'name': '查询嘉宾接口', 'validate': [{'comparator': 'equals', 'check': 'content.message', 'expect': 'success'}]}}
2019-10-09 22:56:49,193 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
TypeError: dumps() takes 1 positional argument but 2 positional arguments (and 3 keyword-only arguments) were given
2019-10-09 23:16:06,355 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/run_test/
Traceback (most recent call last):
KeyError: 'data'
